# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pydefistats

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test getTotalSupply
      run: |
        cd tests
        python GetTotalSupply.py
    - name: Test getName
      run: |
        cd tests
        python GetName.py
    - name: Test getSymbol
      run: |
        cd tests
        python GetSymbol.py
    - name: Test getHolders
      run: |
        cd tests
        python GetHolders.py
    - name: Test getLastExchanges
      run: |
        cd tests
        python GetLastExchanges.py
    - name: Test GetPairsAndLiquidity.py
      run: |
        cd tests
        python GetPairsAndLiquidity.py
    - name: Test GetPrice.py
      run: |
        cd tests
        python GetPrice.py
    - name: Test GetOHLC.py
      run: |
        cd tests
        python GetOHLC.py
